apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  labels:
    app: joker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joker
  template:
    metadata:
      labels:
        app: joker
    spec:
      containers:
      - name: nodeapp
        image: vidyadhar7/nodejs:7
        ports:
          - containerPort: 7500
        env:
        - name: MONGO_URL
          #value: mongodb://mongo:27017
	  value: mongo.helm-deployment.svc.cluster.local
        resources:
          limits:
            cpu: "1"
            memory: "5Gi"
          requests:
            cpu: "500m"
            memory: "500Mi"
